
server:
  port: 9999

spring:
  datasource:
    url: jdbc:h2:./db/headHunter;AUTO_SERVER=true
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver


  liquibase:
    change-log: classpath:/db/changelog/master.yaml


  h2:
    console:
      enabled: true
logging:
  level:
    root: info
  pattern:
    console: "%d{HH:mm:ss} %highlight %-5level %logger{50} %msg%n"
  file:
    name: logs/headHunter.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 5